apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
  - image: foxy-203512/spring-petclinic
    context: .
    jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: 'gcr.io/{{.IMAGE_NAME}}:{{.UUID}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-petclinic
        chartPath: charts/spring-petclinic
        setValueTemplates:
          image.repository: 'gcr.io/{{.IMAGE_NAME}}'
          image.tag: '{{.UUID}}'
